### ISSUE TITLE
Creator Fails

### ISSUE THREAD

**Issue by jscatena88** [DSheirer/jmbe#36]
I have tried on a Manjaro box and on Kubuntu, both fully up to date. And on both I get the following error:

`(base) jason@jason-ThinkPad-X230:~/Workspace/creator-linux-x86_64-v1.0.7$ ./bin/creator
Create JMBE library - starting ....
Created Temporary Work Directory: /tmp/jmbe-creator12221170850678908494
Using Auto-Generated Library Path: /home/jason/Workspace/jmbe-1.0.7.jar
GitHub Downloading: GitHub Release - Name:Version 1.0.7 Version: 1.0.7 HTML URL:https://github.com/DSheirer/jmbe/releases/tag/v1.0.7 Download URL:https://api.github.com/repos/DSheirer/jmbe/zipball/v1.0.7
Downloading Source Code From: https://api.github.com/repos/DSheirer/jmbe/zipball/v1.0.7
Download HTTP Status: 200
Source Code Downloaded to: /tmp/jmbe-creator12221170850678908494/DSheirer-jmbe-v1.0.7-0-g1ce0d87.zip
Looking for required compile libraries here: /home/jason/Workspace/lib
Error creating classpath for compile-time libraries
java.nio.file.NoSuchFileException: /home/jason/Workspace/lib
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(Unknown Source)
        at java.base/java.nio.file.Files.newDirectoryStream(Unknown Source)
        at io.github.dsheirer.jmbe.creator.Creator.getLibraryClassPath(Creator.java:310)
        at io.github.dsheirer.jmbe.creator.Creator.getOptions(Creator.java:242)
        at io.github.dsheirer.jmbe.creator.Creator.process(Creator.java:137)
        at io.github.dsheirer.jmbe.creator.Creator.createLibrary(Creator.java:416)
        at io.github.dsheirer.jmbe.creator.Creator.main(Creator.java:472)
`

**Comment by DSheirer** [comment]
If you cd into the bin directory and execute creator,  does that work?

**Comment by jscatena88** [comment]
Yes it works after moving into the bin directory
