### ISSUE TITLE
Audio stops but can be started again....ERROR i.g.d.a.p.AudioOutput - Error while processing audio buffers  [87MB/640MB 13%]

### ISSUE THREAD

**Issue by RevBaker** [DSheirer/jmbe#52]
JMBE 1.0.9
Linux 5.15.0-92
Mint 21.2

Audio stops soon after monitoring is started with stuttering and buffer issues. All other functions appear to be working normally. The terminal capture reveals:

`13:29:03.446 ERROR i.g.d.a.p.AudioOutput - Error while processing audio buffers  [87MB/640MB 13%]
java.lang.NullPointerException: Cannot invoke "javax.sound.sampled.SourceDataLine.isRunning()" because "this.mOutput" is null
	at io.github.dsheirer.audio.playback.AudioOutput.checkStop(AudioOutput.java:653)
	at io.github.dsheirer.audio.playback.AudioOutput.processAudio(AudioOutput.java:509)
	at io.github.dsheirer.audio.playback.AudioOutput$AudioSegmentProcessor.run(AudioOutput.java:743)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source) `

So when I pull up the Users Preference dialog and Output/Tones and just switch between Audio Output Device selections the audio will resume and then once the error repeats, switch the Source back to the original, the audio starts again. This repeats indefinitely.

**Comment by DSheirer** [comment]
The error looks like you may have switched the audio mixer while channels were decoding and in the middle of playback.  Does this error continue to occur, even when you are not changing the audio output via the User Preferences?

Unfortunately, this error trace doesn't provide a clue as to why you are having issues with audio playback in Linux.

**Comment by RevBaker** [comment]
Continuously and consistently. It's as though a limited  buffer is set up and then it runs out of data, sometimes accompanied by warbling audio as it runs out, sometimes just falls silent. Only changing the output source after the fact of it running out of data does it reset the limited buffer and play again for about 20 to 30 seconds. I've looked at the mixer output  for both ALSA and  Pulse audio and the devices' channels show up, as appropriate, in mono or stereo and nothing happens to them when the event occurs. There is also an issue with the channelization display that either the right or left will show an alias that seems to get stuck and now is also showing numeric IDs for channels not enumerated in the alias list. 

This occurs with v5alpha 6 and any of the v6 flavors. With the initial setup of the program 2 years ago everything worked under v5alpha 6 and was absolutely rock solid. No hardware has been changed. Since this is carrying over between versions now I'm thinking it's something changed in the audio of the base Linux environment. I'll take a look at my change logs and see if there isn't something there.
